# Generated by Django 2.1 on 2020-05-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copy_count',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
