# Generated by Django 2.1.5 on 2020-06-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_first', '0003_auto_20200530_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='friend',
            field=models.ManyToManyField(to='app_first.Friend'),
        ),
    ]
