# Generated by Django 2.1.5 on 2020-06-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_first', '0004_auto_20200607_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='friend',
        ),
        migrations.AddField(
            model_name='friend',
            name='books',
            field=models.ManyToManyField(to='app_first.Book'),
        ),
    ]
