# Generated by Django 2.1.5 on 2020-06-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_first', '0005_auto_20200607_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='book_image/%Y/%m/%d'),
        ),
    ]
